-- CART_AND_BILLING_DETAILS
INSERT INTO CART_AND_BILLING_DETAILS
(BILLING_ID,CART_URL,CURRENCY,DISCOUNT_AMOUNT,GRAND_TOTAL,PROMO_APPLIED,SUBTOTAL,TAX_AMOUNT)
VALUES("BILL101","http://copious.com/","INR",10.00,30.00,"NONE",30.00,10.00);

-- SHIPPING_DETAILS
INSERT INTO SHIPPING_DETAILS
(SHIPPING_ID,SHIPPING_AMOUNT,SHIPPING_DATE,SHIPPING_DETAILS,SHIPPING_TRACKING_URL)
VALUES("SHIP101",20.00,"2021-01-14","Test Shipping","http://copious.com/tracking/NIeX3KYLcPhgRzKy");

-- CART
INSERT INTO CART
(ORDER_ID,EMAIL_ADDRESS,ORDER_DATE,ORDER_PHASE,BILLING_ID,SHIPPING_ID)
VALUES("MM101","mm@gmail.com","2021-01-14","Ready for shipment","BILL101","SHIP101");

-- ITEM
INSERT INTO ITEM
(SKU,CATEGORY,IMAGE_URL,NAME,OTHER,PRODUCT_URL,QUANTITY,SALE_PRICE,TOTAL_PRICE,UNIT_PRICE,ORDER_ID)
VALUES("AB111",1,"http://copious.com/a/p/shirt.jpeg","Shirt","Copious assignment static data","http://copious.com/index.php/shirt.html",2,11.99,23.98,11.99,"MM101");
INSERT INTO ITEM
(SKU,CATEGORY,IMAGE_URL,NAME,OTHER,PRODUCT_URL,QUANTITY,SALE_PRICE,TOTAL_PRICE,UNIT_PRICE,ORDER_ID)
VALUES("AB112",1,"http://copious.com/a/p/shirt.jpeg","Fleece Jacket","A well appointed Fleece jacket","http://copious.com/index.php/shirt.html",2,65.99,55.50,55.50,"MM101");
